BUGFIX:   use the CLASSPATH environment variable when running the examples   and tests to avoid NoClassDefFoundError when CLASSPATH is set properly   but jwsdp.home is not set